name: Random Quote

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch random quote
        run: |
          curl https://zenquotes.io/api/random | jq -r '.[0] | "> \"" + .q + "\" — " + .a' > quote.md

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add quote.md
          git commit -m "update: daily quote" || echo "No changes"
          git push
